var productData = {
	"bowl_1": {
		"mainImage": "images/gallery/bowl_1.jpg",
		"secondImage": "images/gallery/bowl_1.jpg",
		"woodType": "Cherry",
		"finishType": "Walnut Oil",
		"width": '5.75"',
		"height": '2.75"',
		"depth": '2.125"',
		"description": "A general use bowl from a wild cherry tree killed by flood waters a few years before the tree was cut down.  The grain and striations in the wood are amazing.  The tree came from Rock Valley Iowa.",
		"productId": "bowl_1",
	},
	"bowl_2": {
		"mainImage": "images/gallery/bowl_2.jpg",
		"secondImage": "images/gallery/bowl_2.jpg",
		"woodType": "Cherry",
		"finishType": "Walnut Oil",
		"width": '6"',
		"height": '2.125"',
		"depth": '1.75"',
		"description": 'A general use bowl from a wild cherry tree killed by flood waters a few years before the tree was cut down.  The grain and striations in the wood are amazing.  The tree came from Rock Valley, Iowa.',
		"productId": "bowl_2",

	},
	"bowl_3": {
		"mainImage": "images/gallery/bowl_3.jpg",
		"secondImage": "images/gallery/bowl_3.jpg",
		"woodType": "Cherry",
		"finishType": "Walnut Oil",
		"width": '6"',
		"height": '1.875"',
		"depth": '1.125"',
		"description": 'A general use bowl from a wild cherry tree killed by flood waters a few years before the tree was cut down.  The grain and striations in the wood are amazing.  The tree came from Rock Valley, Iowa.',
		"productId": "bowl_3",
	},
	"bowl_4": {
		"mainImage": "images/gallery/bowl_4.jpg",
		"secondImage": "images/gallery/bowl_4.jpg",
		"woodType": "Maple",
		"finishType": "Walnut Oil",
		"width": '8.75"',
		"height": '3.375"',
		"depth": '2.375"',
		"description": 'This wood came from a local banks property.  The tree had died and was cut down.  I obtained a few crotch pieces from the tree (crotch areas are the areas where the tree branched out--and the grain in these areas runs in several directions).  I was able to produce a two similar bowls.  Most of the tree had already deteriorated to very soft unusable mushy wood.',
		"productId": "bowl_4",
	},
	"bowl_5": {
		"mainImage": "images/gallery/bowl_5.jpg",
		"secondImage": "images/gallery/bowl_5.jpg",
		"woodType": "Pine",
		"finishType": "Walnut Oild",
		"width": '6.875"',
		"height": '8"',
		"depth": '1.25"',
		"description": 'This bowl comes from a pine tree from my back yard in NW Iowa which had died of unknown reasons.  Note the blue pine on the edge which is caused by a fungus.  The live edges add to the character of the piece.  A small round bowl on a rectangular footprint.',
		"productId": "bowl_5",

	},
	"bowl_6": {
		"mainImage": "images/gallery/bowl_6.jpg",
		"secondImage": "images/gallery/bowl_6.jpg",
		"woodType": "Pine",
		"finishType": "Walnut Oil",
		"width": '7.25"',
		"height": '2.5"',
		"depth": '1.875"',
		"description": 'This bowl comes from a pine tree from my back yard in NW Iowa which had died of unknown reasons.  Note the blue pine on the edge which is caused by a fungus.  I left some of the inner bark area on the left front of the outer edge',
		"productId": "bowl_6",
	},
	"bowl_7": {
		"mainImage": "images/gallery/bowl_7.jpg",
		"secondImage": "images/gallery/bowl_7.jpg",
		"woodType": "Black Locust",
		"finishType": "Walnut Oil",
		"width": '4.5"',
		"height": '2.5"',
		"depth": '1.5"',
		"description": 'These two bowls are a matched pair coming from a black locust tree which was damaged in an ice storm in NW Iowa.  The wood actually laid in our fire wood pile for about 7 years before I decided to see what might come from an ugly old log.  Place the bowl on the right on top of the other one and it is an exact match--the limb center is the reddish center of each piece.  The colors are amazing. And it came from a chunk of fire wood.  Who knows what is hidden within chunks of wood or from many other things in the world--even people will amaze you when you peel away some of the outer layers.',
		"productId": "bowl_7",
	},
	"bowl_8": {
		"mainImage": "images/gallery/bowl_8.jpg",
		"secondImage": "images/gallery/bowl_8.jpg",
		"woodType": "Walnut",
		"finishType": "Walnut Oil",
		"width": '7.5"',
		"height": '5.125"',
		"depth": '3.5"',
		"description": 'General bowl, from a huge black walnut tree rescued from a tree dump.  Part of the tree was actually on fire when it was pulled from the pile.  Bottom of the trunk was 32 inches in diameter with a very small void in the center; first existing branch was at the 12 foot mark up the trunk. This bowl came from the first branch which was about11 inches in diameter and this branch was on fire when rescued.  The lighter wood is from the outer edge of the branch or the sap wood.  The darker wood is the heart wood of the branch.',
		"productId": "bowl_8",
	},
	"bowl_9": {
		"mainImage": "images/gallery/bowl_9.jpg",
		"secondImage": "images/gallery/bowl_9.jpg",
		"woodType": "Walnut",
		"finishType": "Tung Oil",
		"width": '3.75"',
		"height": '6" (with lid)',
		"depth": '2.5"',
		"description": 'A lidded box from a single segment of a smaller branch from a huge black walnut tree rescued from a tree dump.  Part of the tree was actually on fire when it was pulled from the pile.  Bottom of the trunk was 32 inches in diameter with a very small void in the center; first existing branch was at the 12 foot mark up the trunk.',
		"productId": "bowl_9",
	},
	"bowl_10": {
		"mainImage": "images/gallery/bowl_10.jpg",
		"secondImage": "images/gallery/bowl_10.jpg",
		"woodType": "Walnut",
		"finishType": "Walnut Oil",
		"width": '11.5"',
		"height": '4.25"',
		"depth": '2.25"',
		"description": 'A chip and dip bowl from a huge black walnut tree rescued from a tree dump.  Part of the tree was actually on fire when it was pulled from the pile.  Bottom of the trunk was 32 inches in diameter with a very small void in the center; first existing branch was at the 12 foot mark up the trunk.  There is an indentation in the center of the bowl to hold a small glass bowl for dip.',
		"productId": "bowl_10",
	},
	"bowl_11": {
		"mainImage": "images/gallery/bowl_11.jpg",
		"secondImage": "images/gallery/bowl_11.jpg",
		"woodType": "Walnut",
		"finishType": "Tung Oil",
		"width": '10.625"',
		"height": '2.125"',
		"depth": '1.625"',
		"description": 'General use bowl very wide and shallow; from the trunk a huge black walnut tree rescued from a tree dump.  Part of the tree was actually on fire when it was pulled from the pile.  Bottom of the trunk was 32 inches in diameter with a very small void in the center; first existing branch was at the 12 foot mark up the trunk.',
		"productId": "bowl_11",

	},
		"bowl_12": {
		"mainImage": "images/gallery/bowl_12.jpg",
		"secondImage": "images/gallery/bowl_12.jpg",
		"woodType": "Walnut",
		"finishType": "Tung Oil",
		"width": '7"',
		"height": '3"',
		"depth": '2"',
		"description": 'General bowl, from a huge black walnut tree rescued from a tree dump.  Part of the tree was actually on fire when it was pulled from the pile.  Bottom of the trunk was 32 inches in diameter with a very small void in the center; first existing branch was at the 12 foot mark up the trunk. This bowl received several coats of tung oil and is polished to a high shine to show off the grain and natural beauty of the wood.',
		"productId": "bowl_12",
	},
}